const ROLES = { PATIENT: 'PATIENT', DOCTOR: 'DOCTOR' };

const URGENCY = { NORMAL: 'NORMAL', URGENT: 'URGENT', IMPORTANT: 'IMPORTANT' };

const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
};

module.exports = { ROLES, URGENCY, APPOINTMENT_STATUS };
